# Setup
title:               hyunwk 
tagline:             'A Jekyll theme'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 "https://hyunwk.github.io"
baseurl:             ""
paginate:            5
paginate_path:       "/page:num/" 
permalink:           pretty

# About/contact
author:
  name:              hyunwk
  url:               https://hyunwk.github.io
  email:             42.4.hyunwkim@gmail.com

# Gems
plugins:
  - jekyll-paginate

include:
  - _static

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
